<?php exit();?>
Initializing...|info|13
<?php exit();?>
Creating a job to start Backup|info|17
Starting to Backup Database|info|20
Creating softsql|working|23
Adding (L1) : wpxv_commentmeta table|working|50
Adding (L1) : wpxv_comments table|working|50
Adding (L1) : wpxv_e_events table|working|50
Adding (L1) : wpxv_links table|working|50
Adding (L1) : wpxv_options table|working|50
Adding (L1) : wpxv_postmeta table|working|50
Adding (L1) : wpxv_posts table|working|50
Adding (L1) : wpxv_simply_static_pages table|working|50
Adding (L1) : wpxv_termmeta table|working|50
Adding (L1) : wpxv_terms table|working|50
Adding (L1) : wpxv_term_relationships table|working|50
Adding (L1) : wpxv_term_taxonomy table|working|50
Adding (L1) : wpxv_usermeta table|working|50
Adding (L1) : wpxv_users table|working|50
Adding (L1) : wpxv_wpfront_ure_login_redirect table|working|50
Adding (L1) : wpxv_wpfront_ure_options table|working|50
Adding (L1) : wpxv_wpfront_ure_post_type table|working|50
Adding (L1) : wpxv_wpfront_ure_taxonomy table|working|50
Backing up your Wordpress Install|info|39
Starting to create archive|info|60
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/css/colors|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/css/colors/blue|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/css/colors/midnight|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/css/colors/modern|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/css/colors/ocean|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-admin/network|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/akismet/_inc|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/akismet/_inc/img|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/backuply/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/backuply/lib|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/backuply/lib/Curl|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/css/modules|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/css/modules/container-converter|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/images/app|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/animations|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/dialog|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/e-gallery/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/e-select2|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/e-select2/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/e-select2/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/eicons|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/eicons/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/flatpickr|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/font-awesome/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/font-awesome/fonts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/font-awesome/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/font-awesome/json|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/font-awesome/migration|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/inline-editor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/inline-editor/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/jquery-easing|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/jquery-hover-intent|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/jquery-numerator|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/perfect-scrollbar|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/perfect-scrollbar/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/lib/swiper|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/mask-shapes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/shapes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/assets/svg-paths|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/admin|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/admin/menu|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/admin/menu/interfaces|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/admin/notices|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/admin/ui/components|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/app/admin-menu-items|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/app/modules|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/app/modules/kit-library/connect|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/app/modules/kit-library/data/kits/endpoints|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/app/modules/onboarding|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/app/modules/site-editor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/base/background-process|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/behaviors|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/behaviors/interfaces|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/breakpoints|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/common|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/common/modules|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/common/modules/ajax|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/common/modules/finder|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/debug|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/debug/classes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/dynamic-tags|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/editor/data|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/editor/data/globals|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/editor/data/globals/endpoints|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/experiments/exceptions|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/files|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/files/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/files/file-types|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/frontend/render-modes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/kits/controls|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/logger/items|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/logger/loggers|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/page-assets/data-managers|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/responsive/files|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/settings|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/settings/base|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/settings/editor-preferences|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/settings/page|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/core/utils/import-export/parsers|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/data/v2|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/data/v2/base|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/data/v2/base/endpoint|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/data/v2/base/endpoint/index|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/data/v2/base/exceptions|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/data/v2/base/processor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes/base|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes/editor-templates|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes/interfaces|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes/libraries/wp-background-process|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes/template-library/sources|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/includes/widgets/traits|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/dev-tools|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/elements-color-picker|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/favorites|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/history|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/landing-pages/admin-menu-items|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/library|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/library/documents|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/library/traits|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/page-templates|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/page-templates/templates|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/promotions/admin-menu-items|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/promotions/admin-menu-items/interfaces|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/safe-mode|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/safe-mode/mu-plugin|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/system-info/reporters|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/modules/web-cli|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui/styles/_data|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui/styles/_data/colors|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui/styles/_data/font|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui/styles/_data/spacing|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui/styles/_data/typography|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/elementor/packages/elementor-ui/styles/_maps/typography|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/fonts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/images/templately|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/vendor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/vendor/sweetalert2/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/vendor/sweetalert2/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/lib-edit/quill|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/lib-view|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/lib-view/full-calendar|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/lib-view/magnific-popup|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/lib-view/plyr|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/view|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/edit|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-edit/quill|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/embed|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/full-calendar|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/inview|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/isotope|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/moment|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/plyr|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/tooltipster|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/typeform|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/lib-view/waypoint|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Controls|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Extensions|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Betterdocs-Category-Grid|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Content|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Post-Grid|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Post-Timeline|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Woo-Product-Carousel|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Woo-Product-Gallery|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Template/Woocommerce/Checkout|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/templates|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/assets/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/assets/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/assets/js/chosen|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/add-remove-cap|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/integration/plugins/duplicator|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/login-redirect|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/nav-menu|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/restore|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/settings|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/shortcodes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/taxonomies|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/includes/widget|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/wpfront-user-role-editor/languages|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/central|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/central/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/images/addons-images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/images/icons|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/images/notices|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/Dropbox2/OAuth/Consumer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/Google|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/Google/Cache|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/Google/Service|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/Google/Task|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/cloudfiles|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/handlebars|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/jquery-ui.dialog.extended|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/jstree/themes/default|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/includes/labelauty|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/languages|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/templates/wp-admin|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/templates/wp-admin/advanced|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-crt-php/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-crt-php/src/AWS|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-crt-php/src/AWS/CRT/Auth|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-crt-php/src/AWS/CRT/Internal|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Api|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Api/Serializer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Arn|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Arn/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Arn/S3|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/ClientSideMonitoring|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Endpoint|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Endpoint/UseDualstackEndpoint|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/EndpointDiscovery/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Handler|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Keyspaces|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Keyspaces/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/Retry/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/S3/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/S3/RegionalEndpoint|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/S3/RegionalEndpoint/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/S3/UseArnRegion|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/data/iam|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/data/iam/2010-05-08|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/aws/aws-sdk-php/src/data/s3|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/components|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/composer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/eher/oauth|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/eher/oauth/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/eher/oauth/src/Eher|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Batch|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Batch/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Http|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Http/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Header|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Inflection|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Iterator|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Log|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Parser/Message|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Plugin/ErrorResponse|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Plugin/ErrorResponse/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Plugin/History|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Plugin/Log|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Plugin/Md5|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Plugin/Oauth|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Service|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Service/Builder|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Service/Command/LocationVisitor/Response|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzle/guzzle/src/Guzzle/Service/Resource|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/guzzle|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/guzzle/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/guzzle/src/Cookie|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/guzzle/src/Handler|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/promises|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/psr7|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/guzzlehttp/psr7/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/mikemccabe|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/mikemccabe/json-patch-php|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/mikemccabe/json-patch-php/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/mtdowling/jmespath.php/bin|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/paragonie/random_compat/dist|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/paragonie/random_compat/lib|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/phpseclib|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/phpseclib/phpseclib|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/phpseclib/phpseclib/phpseclib/Crypt|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/phpseclib/phpseclib/phpseclib/File|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/phpseclib/phpseclib/phpseclib/System|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/psr|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/psr/http-message|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/psr/http-message/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/psr/log|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/psr/log/Psr|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/psr/log/Psr/Log|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/CDN|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/Common/Exceptions|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/Common/Resource|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/Identity|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/Identity/Resource|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Constants|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Upload|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/ralouphie|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/ralouphie/getallheaders|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/ralouphie/getallheaders/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/event-dispatcher|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/event-dispatcher/Debug|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-intl-idn|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-intl-idn/Resources|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-intl-normalizer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-intl-normalizer/Resources/unidata|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-mbstring|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-php70|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-php70/Resources|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/symfony/polyfill-php72|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft/common-libs|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft/common-libs/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft/common-libs/src/updraft-notices|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft/common-libs/src/updraft-rpc|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft/common-libs/src/updraft-semaphore|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/updraftplus/vendor/team-updraft/common-libs/src/updraft-tasks|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/languages|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/src/models|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/src/tasks|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/a5hleyrich|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/css-selector/Exception|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/css-selector/Parser|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/css-selector/Parser/Handler|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/css-selector/Parser/Shortcut|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/css-selector/XPath/Extension|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-iconv/Resources/charset|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-intl-normalizer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-intl-normalizer/Resources|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-mbstring/Resources|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-mbstring/Resources/unidata|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-php80|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/symfony/polyfill-php80/Resources|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-ascii|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-ascii/build/docs|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-ascii/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-ascii/src/voku/helper|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-ascii/src/voku/helper/data|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-utf8|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-utf8/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-utf8/src/voku/helper|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/portable-utf8/src/voku/helper/data|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/simple_html_dom/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/simply-static/vendor/voku/simple_html_dom/src/voku/helper|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/plugins/post-type-switcher/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwenty|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwenty/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwenty/assets/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwenty/assets/fonts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwenty/assets/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwenty/template-parts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/01-settings|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/02-tools|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/03-generic|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/04-elements|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/audio|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/heading|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/image|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/latest-comments|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/latest-posts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/navigation|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/paragraph|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/preformatted|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/query-loop|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/quote|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/rss|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/search|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/tag-clould|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/assets/sass/05-blocks/verse|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/inc|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/template-parts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentyone/template-parts/excerpt|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/assets/fonts/dm-sans|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/assets/fonts/ibm-plex|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/assets/fonts/inter|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/assets/videos|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/inc|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/inc/patterns|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/styles|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/twentytwentytwo/templates|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/css/blog|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/css/learndash|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/css/third|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/fonts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/fonts/fontawesome|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/fonts/fontawesome/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/fonts/slick|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/fonts/star|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/img|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/img/photoswipe|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/js/wp-plugins/easy-digital-downloads|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/js/wp-plugins/woocommerce|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/theme|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/theme/menu|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/theme/mobile-menu|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/theme/search|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/wp-plugins|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/wp-plugins/easy-digital-downloads|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/assets/src/js/wp-plugins/woocommerce|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/fonts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/img|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/min/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/src|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/src/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/assets/src/js/components|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/controls|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/controls/dimensions|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/controls/dropdown-pages|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/controls/multiple-select|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/controls/textarea|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/controls/upsell|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/customizer/library|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/themepanel|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/themepanel/assets/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/themepanel/assets/js|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/themepanel/views/panes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/third|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/walker|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/walker/assets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/inc/woocommerce|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/languages|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/entry/media|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/entry/thumbnail-style|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/header|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/mobile|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/page|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/single|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/single/media|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/partials/topbar|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/components|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/components/footer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/components/header|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/components/mobile|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/components/sidebar|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/edd|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/learndash|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/sass/woo|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/templates|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/tribe-events|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/themes/oceanwp/woocommerce/single-product|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/uploads/2022|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-content/uploads/2022/09|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/block-patterns|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/audio|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/buttons|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/calendar|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/column|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/comment-author-name|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/comment-content|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/comment-date|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/comments-pagination-numbers|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/cover|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/embed|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/freeform|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/group|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/html|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/image|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/latest-comments|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/list|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/missing|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/navigation|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/navigation-link|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/page-list|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/paragraph|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/pattern|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/post-author|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/post-author-biography|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/post-comments-form|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/post-date|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/post-navigation-link|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/post-title|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/pullquote|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/query-pagination|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/query-pagination-numbers|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/query-pagination-previous|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/query-title|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/quote|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/read-more|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/site-logo|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/site-tagline|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/social-links|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/tag-cloud|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/text-columns|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/blocks/verse|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/block-directory|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/block-editor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/block-library|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/components|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/customize-widgets|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/edit-post|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/editor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/format-library|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/css/dist/reusable-blocks|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/customize|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/fonts|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/ID3|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/images/crystal|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/images/media|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/images/smilies|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/images/wlw|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/crop|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/dist|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/dist/development|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/imgareaselect|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/jcrop|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/jquery/ui|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/mediaelement|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/plupload|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/langs|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/compat3x|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/compat3x/css|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/fullscreen|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/image|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/lists|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/paste|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/tabfocus|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/textcolor|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/wordpress|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/plugins/wptextpattern|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/skins|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/skins/lightgray|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/skins/lightgray/img|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/skins/wordpress|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/skins/wordpress/images|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/themes|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/themes/modern|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/js/tinymce/utils|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/php-compat|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/random_compat|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Auth|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Cookie|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Exception/HTTP|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Exception/Transport|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Proxy|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Response|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Requests/Transport|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/rest-api/search|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/SimplePie/Content|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/SimplePie/Content/Type|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/SimplePie/Parse|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sitemaps|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/lib|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/namespaced|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/namespaced/Core|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/namespaced/Core/ChaCha20|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/namespaced/Core/Curve25519|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/namespaced/Core/Poly1305|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/src/Core/Base64|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/src/Core/Curve25519/Ge|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/src/Core32/Curve25519|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/src/Core32/SecretStream|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/sodium_compat/src/PHP52|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/Text/Diff/Renderer|adding|65
Adding (L1) : /home/xpkjvfwlhosting/public_html/wp-includes/theme-compat|adding|65
Archive created with a file size of 55.89 MB|info|100
Backup Successfully Completed|success|100
